[dosbox]
machine  = svga_s3
memsize  = 16

[cpu]
core     = dynamic
cputype  = 386
cycles   = max

[dos]
xms = true
ems = true
umb = true

[mouse]
mouse = true

[autoexec]
mount c .
c:
keypad.exe
pause
